GCC=gcc
CFLAGS=-c -g -Wall
LFLAGS=-lreadline
EXE=aysussa

all: ${EXE}.o
    ${GCC} ${EXE}.o -o ${EXE} ${LFLAGS} 

${EXE}.o: ${EXE}.c
    ${GCC} ${CFLAGS} ${EXE}.c

clean:
    rm -rf *.o
    rm -rf ${EXE}
